In [3]:
!pip3 install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 1.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 14.9 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 16.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 3.9 MB/s eta 0:00:0000:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 19.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 3.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 7.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 28.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 12.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 3.7 MB/s eta 0:00:0000:0100:01
     ━━━━━

Most everyday mathematics consists of manipulating numbers one at a time. Formally, we call these values scalars. For example, the temperature in Palo Alto is a balmy 72 degrees Fahrenheit. If you wanted to convert the temperature to Celsius you would evaluate the expression, setting to c = 5/9*(f-32) In this equation, the values 
5,9, and 32 are scalars. The variables c and f represent unknown scalars.

refer scalar from this link http://preview.d2l.ai/d2l-en/master/chapter_preliminaries/linear-algebra.html

In [7]:
import torch
x = torch.tensor(2.0)
y = torch.tensor(3.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(-1.), tensor(6.), tensor(0.6667), tensor(8.))

vectors as fixed-length arrays of scalars.

In [12]:
x = torch.arange(5)
x

tensor([0, 1, 2, 3, 4])

In [ ]:
We can refer to an element of a vector by using a subscript. For example, x subscript 2 denotes the second element of 
x. Since x subscript 2 is a scalar, we do not bold it. By default, we visualize vectors by stacking their elements vertically.

<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable displaystyle="true" columnalign="right" columnspacing="0em" rowspacing="3pt">
    <mtr>
      <mtd>
        <mrow data-mjx-texclass="ORD">
          <mi mathvariant="bold">x</mi>
        </mrow>
        <mo>=</mo>
        <mrow data-mjx-texclass="INNER">
          <mo data-mjx-texclass="OPEN">[</mo>
          <mtable columnalign="center" columnspacing="1em" rowspacing="4pt">
            <mtr>
              <mtd>
                <msub>
                  <mi>x</mi>
                  <mrow data-mjx-texclass="ORD">
                    <mn>1</mn>
                  </mrow>
                </msub>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mrow data-mjx-texclass="ORD">
                  <mo>&#x22EE;</mo>
                </mrow>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <msub>
                  <mi>x</mi>
                  <mrow data-mjx-texclass="ORD">
                    <mi>n</mi>
                  </mrow>
                </msub>
              </mtd>
            </mtr>
          </mtable>
          <mo data-mjx-texclass="CLOSE">]</mo>
        </mrow>
        <mo>,</mo>
      </mtd>
    </mtr>
  </mtable>
</math>

In [13]:
x[3]

tensor(3)

To indicate that a vector contains n elements, we write

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow data-mjx-texclass="ORD">
    <mi mathvariant="bold">x</mi>
  </mrow>
  <mo>&#x2208;</mo>
  <msup>
    <mrow data-mjx-texclass="ORD">
      <mi mathvariant="double-struck">R</mi>
    </mrow>
    <mi>n</mi>
  </msup>
</math>

Formally, we call n the dimensionality of the vector. In code, this corresponds to the tensor’s length, accessible via Python’s built-in len function.

In [14]:
len(x)

5

We can also access the length via the shape attribute. The shape is a tuple that indicates a tensor’s length along each axis. Tensors with just one axis have shapes with just one element.

In [16]:
x.shape

torch.Size([5])

In [17]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Sometimes, we want to flip the axes. When we exchange a matrix’s rows and columns, the result is called its transpose. 

In [18]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matrices are the subset of square matrices that are equal to their own transposes: 
. The following matrix is symmetric:

In [20]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [21]:
A.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [25]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

While you can go far in your machine learning journey with only scalars, vectors, and matrices, eventually you may need to work with higher-order tensors. Tensors give us a generic way to describe extensions to nth 
-order arrays. 

In [24]:
torch.arange(30).reshape(3,2,5)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])